import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="bg-gradient-to-r from-red-700/90 to-blue-500/90 max-w-7xl mx-auto">
        <main className="bg-black shadow-2xl drop-shadow-2xl rounded-md p-4 text-white">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
